

export const LAYOUT_CELL_WRITE_MULTIPLE = 'LAYOUT_CELL_WRITE_MULTIPLE'

export const LAYOUT_CELL_TOGGLE = 'LAYOUT_CELL_TOGGLE'

export const LAYOUT_CELL_WALL_TOGGLE = 'LAYOUT_CELL_WALL_TOGGLE'
export const LAYOUT_CELL_FLOOR_TOGGLE = 'LAYOUT_CELL_FLOOR_TOGGLE'
export const LAYOUT_CELL_SLUDGE_TOGGLE = 'LAYOUT_CELL_SLUDGE_TOGGLE'

export const LAYOUT_CELL_DRAG_START = 'LAYOUT_CELL_DRAG_START'
export const LAYOUT_CELL_DRAG_ENTER = 'LAYOUT_CELL_DRAG_ENTER'
export const LAYOUT_CELL_DRAG_DROP = 'LAYOUT_CELL_DRAG_DROP'

export const UI_PAINTER_BRUSH_WALL = 'UI_PAINTER_BRUSH_WALL'
export const UI_PAINTER_BRUSH_SLUDGE = 'UI_PAINTER_BRUSH_SLUDGE'

export const UI_PAINTER_STRENGTH_SET = 'UI_PAINTER_STRENGTH_SET'